config/routes.rb
Rails.application.routes.draw do
  root "pages#home" #creates root_path
  get "about" => "pages#about" # creates about_path
  get "shop" => "pages#shop" # creates shop_path
  get "gifts" => "pages#gifts" # creates about_path

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
  
  def shop
  end

  def gifts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Green Pea Cookie</a>
    </div>

    
      <ul class="nav navbar-nav navbar-right">

        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Shop Here", shop_path %></li>
        <li><%= link_to "Gifting", gifts_path %></li>
        <li><%= link_to "About Us", about_path %></li>

       </ul>        


<!-- 
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
 -->

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
	<!DOCTYPE html>
<html>
<head>
  <title>Gpc</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<!-- Viewport to recognize use on mobile device -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>
	
	<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/about.html.erb
<h1> About Us </h1>
<p> Getting High on Coding </p>

app/views/pages/gifts.html.erb
<h1> Best thing in life is to be able to give </h1>
<p> Spamming with you some Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae, architecto obcaecati facilis culpa temporibus numquam, laborum veniam eaque consectetur doloribus a eum soluta corporis explicabo expedita consequatur similique magnam, natus. </p>

app/views/pages/home.html.erb
<h1>Start Of The Green Pea Cookie Movement</h1>
<p>Get your Green Pea Cookie Sample <%= link_to "Here", "#" %> </p>

app/views/pages/shop.html.erb
<h1> Its shopping time! </h1>
<p> Buy one get one free!!!! </p>